/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class VistaLogin extends javax.swing.JFrame {

	/**
	 * Creates new form VistaLogin
	 */
	public VistaLogin() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jButton1Conectar = new javax.swing.JButton();
		jButton2Salir = new javax.swing.JButton();
		jComboBox1Servidores = new javax.swing.JComboBox<>();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Acceso a la Aplicacion ");

		jLabel1.setText("Servidor");

		jButton1Conectar.setText("Conectar");
		jButton1Conectar.setToolTipText("");
		jButton1Conectar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ConectarActionPerformed(evt);
			}
		});

		jButton2Salir.setText("Salir");
		jButton2Salir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2SalirActionPerformed(evt);
			}
		});

		jComboBox1Servidores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "MariaDB" }));
		jComboBox1Servidores.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ServidoresActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(143, Short.MAX_VALUE).addComponent(jButton1Conectar)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton2Salir)
						.addGap(17, 17, 17))
				.addGroup(layout.createSequentialGroup().addGap(41, 41, 41).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jComboBox1Servidores, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(35, 35, 35)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(jComboBox1Servidores, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jButton1Conectar).addComponent(jButton2Salir))
				.addGap(20, 20, 20)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2SalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2SalirActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton2SalirActionPerformed

	private void jComboBox1ServidoresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ServidoresActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox1ServidoresActionPerformed

	private void jButton1ConectarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ConectarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton1ConectarActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public javax.swing.JButton jButton1Conectar;
	public javax.swing.JButton jButton2Salir;
	public javax.swing.JComboBox<String> jComboBox1Servidores;
	public javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables
}
