/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author JoseAngelRD
 */
public class VistaCRUDSocio extends javax.swing.JDialog {

	/**
	 * Creates new form VistaCRUDMonitor
	 */
	public VistaCRUDSocio() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane5 = new javax.swing.JScrollPane();
		jTextPane5 = new javax.swing.JTextPane();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jTextFieldCodSocio = new javax.swing.JTextField();
		jTextFieldNomSocio = new javax.swing.JTextField();
		jTextFieldDNISocio = new javax.swing.JTextField();
		jTextFieldTelfSocio = new javax.swing.JTextField();
		jTextFieldCorreoSocio = new javax.swing.JTextField();
		jTextFieldCategoriaSocio = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jDateChooserEntrada = new com.toedter.calendar.JDateChooser();
		jLabel8 = new javax.swing.JLabel();
		jDateChooserNac = new com.toedter.calendar.JDateChooser();

		jTextPane5.setText("  Nombre");
		jScrollPane5.setViewportView(jTextPane5);

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Nuevo Monitor");

		jLabel1.setText("  Socio");

		jLabel2.setText("Nombre");

		jLabel3.setText("DNI");

		jLabel4.setText("Telefono");

		jLabel5.setText("Correo");

		jLabel6.setText("Fecha Entrada");

		jLabel7.setText("   Categoria");

		jTextFieldCodSocio.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldCodSocioActionPerformed(evt);
			}
		});

		jTextFieldNomSocio.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldNomSocioActionPerformed(evt);
			}
		});

		jTextFieldDNISocio.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldDNISocioActionPerformed(evt);
			}
		});

		jTextFieldTelfSocio.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldTelfSocioActionPerformed(evt);
			}
		});

		jTextFieldCorreoSocio.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldCorreoSocioActionPerformed(evt);
			}
		});

		jTextFieldCategoriaSocio.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldCategoriaSocioActionPerformed(evt);
			}
		});

		jButton1.setText("Insertar");

		jButton2.setText("Cancelar");

		jLabel8.setText("Fecha Nacimiento");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout
								.createSequentialGroup().addGap(23, 23, 23)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(
												layout.createSequentialGroup().addComponent(jLabel3).addGap(15, 15, 15))
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addGap(27, 27, 27)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jTextFieldCodSocio,
														javax.swing.GroupLayout.PREFERRED_SIZE, 53,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(119, 119, 119))
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jTextFieldNomSocio).addComponent(jTextFieldDNISocio))
												.addGap(41, 41, 41))))
								.addGroup(layout.createSequentialGroup().addContainerGap(12, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(layout.createSequentialGroup().addComponent(jLabel8)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(jDateChooserNac,
																javax.swing.GroupLayout.PREFERRED_SIZE, 116,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup().addComponent(jLabel4)
														.addGap(27, 27, 27).addComponent(jTextFieldTelfSocio,
																javax.swing.GroupLayout.PREFERRED_SIZE, 131,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(41, 41, 41)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
								.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												layout.createSequentialGroup().addGap(11, 11, 11).addComponent(jLabel5))
										.addComponent(jLabel7))
								.addGap(32, 32, 32)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextFieldCorreoSocio, javax.swing.GroupLayout.PREFERRED_SIZE,
												113, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextFieldCategoriaSocio, javax.swing.GroupLayout.PREFERRED_SIZE,
												113, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(0, 2, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel6).addGap(18, 18, 18)
										.addComponent(jDateChooserEntrada, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
						.addGroup(layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton1).addGap(18, 18, 18).addComponent(jButton2).addGap(12, 12, 12)))
				.addGap(15, 15, 15)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(14, 14, 14)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(jTextFieldCodSocio,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(jTextFieldNomSocio, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(jTextFieldDNISocio,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5)
								.addComponent(jTextFieldCorreoSocio, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jDateChooserEntrada,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7).addComponent(jTextFieldCategoriaSocio,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addComponent(jLabel6))))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jDateChooserNac,
								javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
						.addComponent(jTextFieldTelfSocio, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1).addComponent(jButton2))
				.addGap(16, 16, 16)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextFieldCodSocioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCodSocioActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldCodSocioActionPerformed

	private void jTextFieldNomSocioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldNomSocioActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldNomSocioActionPerformed

	private void jTextFieldDNISocioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldDNISocioActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldDNISocioActionPerformed

	private void jTextFieldTelfSocioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldTelfSocioActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldTelfSocioActionPerformed

	private void jTextFieldCorreoSocioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCorreoSocioActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldCorreoSocioActionPerformed

	private void jTextFieldCategoriaSocioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCategoriaSocioActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldCategoriaSocioActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public javax.swing.JButton jButton1;
	public javax.swing.JButton jButton2;
	public com.toedter.calendar.JDateChooser jDateChooserEntrada;
	public com.toedter.calendar.JDateChooser jDateChooserNac;
	public javax.swing.JLabel jLabel1;
	public javax.swing.JLabel jLabel2;
	public javax.swing.JLabel jLabel3;
	public javax.swing.JLabel jLabel4;
	public javax.swing.JLabel jLabel5;
	public javax.swing.JLabel jLabel6;
	public javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JScrollPane jScrollPane5;
	public javax.swing.JTextField jTextFieldCategoriaSocio;
	public javax.swing.JTextField jTextFieldCodSocio;
	public javax.swing.JTextField jTextFieldCorreoSocio;
	public javax.swing.JTextField jTextFieldDNISocio;
	public javax.swing.JTextField jTextFieldNomSocio;
	public javax.swing.JTextField jTextFieldTelfSocio;
	private javax.swing.JTextPane jTextPane5;
	// End of variables declaration//GEN-END:variables
}
