/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author JoseAngelRD
 */
public class VistaCRUDMonitor extends javax.swing.JDialog {

	/**
	 * Creates new form VistaCRUDMonitor
	 */
	public VistaCRUDMonitor() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane5 = new javax.swing.JScrollPane();
		jTextPane5 = new javax.swing.JTextPane();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jTextFieldCodMonitor = new javax.swing.JTextField();
		jTextFieldNomMonitor = new javax.swing.JTextField();
		jTextFieldDNIMonitor = new javax.swing.JTextField();
		jTextFieldTelfMonitor = new javax.swing.JTextField();
		jTextFieldCorreoMonitor = new javax.swing.JTextField();
		jTextFieldNickMonitor = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jDateChooserCalendario = new com.toedter.calendar.JDateChooser();

		jTextPane5.setText("  Nombre");
		jScrollPane5.setViewportView(jTextPane5);

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Nuevo Monitor");

		jLabel1.setText("Codigo");

		jLabel2.setText("Nombre");

		jLabel3.setText("DNI");

		jLabel4.setText("Telefono");

		jLabel5.setText("Correo");

		jLabel6.setText("Fecha Entrada");

		jLabel7.setText("Nick");

		jTextFieldCodMonitor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldCodMonitorActionPerformed(evt);
			}
		});

		jTextFieldNomMonitor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldNomMonitorActionPerformed(evt);
			}
		});

		jTextFieldDNIMonitor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldDNIMonitorActionPerformed(evt);
			}
		});

		jTextFieldTelfMonitor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldTelfMonitorActionPerformed(evt);
			}
		});

		jTextFieldCorreoMonitor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldCorreoMonitorActionPerformed(evt);
			}
		});

		jButton1.setText("Insertar");

		jButton2.setText("Cancelar");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(21, 21, 21)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel1).addComponent(jLabel2).addComponent(jLabel4)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel3).addGap(15, 15, 15)))
						.addGap(27, 27, 27)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jTextFieldTelfMonitor, javax.swing.GroupLayout.PREFERRED_SIZE,
												131, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jTextFieldCodMonitor,
														javax.swing.GroupLayout.PREFERRED_SIZE, 53,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(119, 119, 119))
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jTextFieldNomMonitor).addComponent(jTextFieldDNIMonitor))
												.addGap(41, 41, 41)))
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup().addGap(11, 11, 11)
																.addComponent(jLabel5))
														.addGroup(layout.createSequentialGroup().addGap(26, 26, 26)
																.addComponent(jLabel7)))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextFieldCorreoMonitor,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 113,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jTextFieldNickMonitor,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 113,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(layout.createSequentialGroup().addGap(26, 26, 26)
														.addComponent(jButton1).addGap(18, 18, 18)
														.addComponent(jButton2).addGap(0, 1, Short.MAX_VALUE))
												.addGroup(layout.createSequentialGroup().addComponent(jLabel6)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jDateChooserCalendario,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
										.addGap(40, 40, 40)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(23, 23, 23)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(jTextFieldCodMonitor,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(jTextFieldNomMonitor, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(jTextFieldDNIMonitor,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5)
								.addComponent(jTextFieldCorreoMonitor, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jDateChooserCalendario,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7).addComponent(jTextFieldNickMonitor,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addComponent(jLabel6))))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
						.addComponent(jTextFieldTelfMonitor, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1).addComponent(jButton2))
				.addContainerGap(34, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextFieldCodMonitorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCodMonitorActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldCodMonitorActionPerformed

	private void jTextFieldNomMonitorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldNomMonitorActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldNomMonitorActionPerformed

	private void jTextFieldDNIMonitorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldDNIMonitorActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldDNIMonitorActionPerformed

	private void jTextFieldTelfMonitorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldTelfMonitorActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldTelfMonitorActionPerformed

	private void jTextFieldCorreoMonitorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCorreoMonitorActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldCorreoMonitorActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public javax.swing.JButton jButton1;
	public javax.swing.JButton jButton2;
	public com.toedter.calendar.JDateChooser jDateChooserCalendario;
	public javax.swing.JLabel jLabel1;
	public javax.swing.JLabel jLabel2;
	public javax.swing.JLabel jLabel3;
	public javax.swing.JLabel jLabel4;
	public javax.swing.JLabel jLabel5;
	public javax.swing.JLabel jLabel6;
	public javax.swing.JLabel jLabel7;
	private javax.swing.JScrollPane jScrollPane5;
	public javax.swing.JTextField jTextFieldCodMonitor;
	public javax.swing.JTextField jTextFieldCorreoMonitor;
	public javax.swing.JTextField jTextFieldDNIMonitor;
	public javax.swing.JTextField jTextFieldNickMonitor;
	public javax.swing.JTextField jTextFieldNomMonitor;
	public javax.swing.JTextField jTextFieldTelfMonitor;
	private javax.swing.JTextPane jTextPane5;
	// End of variables declaration//GEN-END:variables
}
