/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class VistaMenu extends javax.swing.JFrame {

	/**
	 * Creates new form VistaMenu
	 */
	public VistaMenu() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenu5 = new javax.swing.JMenu();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		jMenuItem4 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(1000, 500));

		jMenu1.setText("Monitores");

		jMenuItem1.setText("Gestion de Monitores");
		jMenuItem1.setVerifyInputWhenFocusTarget(false);
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem2.setText("Cuota de Monitor");
		jMenu1.add(jMenuItem2);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Socios");

		jMenuItem3.setText("Gestion de Socios");
		jMenu2.add(jMenuItem3);

		jMenuBar1.add(jMenu2);

		jMenu3.setText("Actividades");
		jMenuBar1.add(jMenu3);

		jMenu5.setText("Limpiar");

		jMenuItem5.setText("Limpiar Pantalla");
		jMenu5.add(jMenuItem5);

		jMenuBar1.add(jMenu5);

		jMenu4.setText("Salir");

		jMenuItem4.setText("Salir de la aplicacion");
		jMenuItem4.setActionCommand("Salir");
		jMenu4.add(jMenuItem4);
		jMenuItem4.getAccessibleContext().setAccessibleName("Salir");

		jMenuBar1.add(jMenu4);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1000, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	public javax.swing.JMenu jMenu3;
	public javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenuBar jMenuBar1;
	public javax.swing.JMenuItem jMenuItem1;
	public javax.swing.JMenuItem jMenuItem2;
	public javax.swing.JMenuItem jMenuItem3;
	public javax.swing.JMenuItem jMenuItem4;
	public javax.swing.JMenuItem jMenuItem5;
	// End of variables declaration//GEN-END:variables
}
